#!/usr/bin/env python3
"""
Generate assets/js/tracks.js from files in assets/audio.
Usage:
  python tools/generate_tracks.py      # generate once
  python tools/generate_tracks.py --watch   # regenerate on changes (simple polling watcher)

Drop your MP3/OGG files into assets/audio/ and run the script.
"""
import os
import json
import argparse
import time

ROOT = os.path.dirname(os.path.dirname(__file__))
AUDIO_DIR = os.path.join(ROOT, 'assets', 'audio')
OUT_FILE = os.path.join(ROOT, 'assets', 'js', 'tracks.js')
EXTS = ('.mp3', '.ogg', '.wav', '.m4a')


def scan_and_write():
    if not os.path.isdir(AUDIO_DIR):
        print('No audio directory found at', AUDIO_DIR)
        return
    files = [f for f in sorted(os.listdir(AUDIO_DIR)) if f.lower().endswith(EXTS)]
    paths = [os.path.join('assets', 'audio', f).replace('\\','/') for f in files]
    data = 'window.AUDIO_TRACKS = ' + json.dumps(paths, indent=2) + ';\n'
    with open(OUT_FILE, 'w', encoding='utf-8') as fh:
        fh.write('// generated by tools/generate_tracks.py\n')
        fh.write(data)
    print('Wrote', OUT_FILE, 'with', len(paths), 'tracks')


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--watch', action='store_true', help='Watch folder and regenerate on changes')
    args = p.parse_args()
    if not args.watch:
        scan_and_write()
        return

    last = None
    print('Watching', AUDIO_DIR, 'for changes. Press Ctrl+C to stop.')
    try:
        while True:
            files = None
            if os.path.isdir(AUDIO_DIR):
                files = [f for f in sorted(os.listdir(AUDIO_DIR)) if f.lower().endswith(EXTS)]
            if files is None: files = []
            key = '\n'.join(files)
            if key != last:
                scan_and_write()
                last = key
            time.sleep(2)
    except KeyboardInterrupt:
        print('\nStopped watcher')

if __name__ == '__main__':
    main()
