@echo off
REM Generate assets/js/tracks.js from files in assets/audio (Windows)
SETLOCAL ENABLEDELAYEDEXPANSION
set ROOT=%~dp0\..
set AUD=%~dp0\..\assets\audio
set OUT=%~dp0\..\assets\js\tracks.js
if not exist "%AUD%" mkdir "%AUD%"
powershell -NoProfile -Command " $files = Get-ChildItem -Path '%AUD%' -Include '*.mp3','*.ogg','*.wav','*.m4a' -File -ErrorAction SilentlyContinue | Sort-Object Name; $paths = $files | ForEach-Object { ('assets/audio/' + $_.Name) -replace '\\\\','/' }; $json = $paths | ConvertTo-Json -Depth 1; $out = '// generated by tools\\generate_tracks.bat\n' + 'window.AUDIO_TRACKS = ' + $json + ';'; Set-Content -Path '%OUT%' -Value $out -Encoding UTF8; Write-Host 'Wrote' '%OUT%' 'with' ($paths.Count) 'tracks' "

echo Done.
pause
